name: NPM Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run prepack
      - run: npm audit signatures
      - name: Publish to NPM
        run: npm publish --access public ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
